## Project Description

The goal of this project is accurate analysis of sentiment of twit. The Training dataset contains different-different twits and with respect to sentiment of tweet. We are here training our model on training data calculate the training loss and then we are evaluate our model on validation data.

### Objectives



*   **Data Preprocessing** : Cleaning and Preparing the text data for training.
*   **Tokenization** : Tokenizing the text data for model understanding.


*   **Loading Model** : Loading model for text sentiment prediction.

*   **Training** : Train our model on training data.
*   **Validation** : Evaluating model on validation text data.

### About the Dataset
This dataset contains 4 columns : tweet_id, entity, tweet_content, and sentiment. With the help of tweet_id, entity, tweet_content we have to predict sentiment of tweet and evaluate our model.

*   **Dataset** : Twitter-Sentiment-Analysis
*   **Content** : Data on various tweets text
*   **Number of rows** : 74681
*   **Number of columns** : 4

## Import the Libraries

In [ ]:
import pandas as pd
import numpy as np### math computations
import sklearn### machine learning library
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re # for Regular Expressions
import string
import nltk
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder
from google.colab import files
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, DefaultDataCollator, Trainer

In [ ]:
uploaded = files.upload()

Saving twitter_training.csv to twitter_training.csv

In [ ]:
uploaded = files.upload()

Saving twitter_validation.csv to twitter_validation.csv

## Read the Dataset

In [ ]:
df=pd.read_csv('twitter_training.csv')

In [ ]:
df2=pd.read_csv('twitter_validation.csv')

In [ ]:
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

## Rename the Columns

In [ ]:
df.columns=['tweet_id','entity','sentiment','tweet_content']

In [ ]:
df2.columns=['tweet_id','entity','sentiment','tweet_content']

In [ ]:
df.head()

,tweet_id,entity,sentiment,tweet_content
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

## Checking Missing Values

In [ ]:
df.isnull().sum()

tweet_id           0
entity             0
sentiment          0
tweet_content    686
dtype: int64

## Checking Duplicates

In [ ]:
df.duplicated().sum()

np.int64(2700)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df[df['tweet_content'].notnull()]

In [ ]:
df.isnull().sum()

tweet_id         0
entity           0
sentiment        0
tweet_content    0
dtype: int64

## Dropping Unnecessary Columns

In [ ]:
df.drop(columns=['tweet_id','entity'],inplace=True)

In [ ]:
df2.drop(columns=['tweet_id','entity'],inplace=True)

In [ ]:
df2.duplicated().sum()

np.int64(1)

In [ ]:
df.head(1)

  sentiment                                      tweet_content
0  Positive  I am coming to the borders and I will kill you...

## Cleaning the Text Data

In [ ]:
def remove_html_tags(text):
    pattern="<.*?>"
    clean_text=re.sub(pattern,'',text)
    return clean_text

In [ ]:
df['tweet_content']=df['tweet_content'].apply(remove_html_tags)

In [ ]:
df2['tweet_content']=df2['tweet_content'].apply(remove_html_tags)

In [ ]:
def remove_urls(text):
    pattern='https?://\S+'
    new_text=re.sub(pattern,'',text)
    return new_text

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_514/1449429058.py:2: SyntaxWarning: invalid escape sequence '\S'
  pattern='https?://\S+'

In [ ]:
df['tweet_content']=df['tweet_content'].apply(remove_urls)

In [ ]:
df2['tweet_content']=df2['tweet_content'].apply(remove_urls)

In [ ]:
def remove_newline(text):
    pattern='\n'
    new_text=re.sub(pattern,'',text)
    return new_text

In [ ]:
df2['tweet_content']=df2['tweet_content'].apply(remove_newline)

In [ ]:
exclude=list(string.punctuation)

In [ ]:
def remove_punctuation(text):
    for i in exclude:
        text=text.replace(i,'')
    return text

In [ ]:
df['tweet_content']=df['tweet_content'].apply(remove_punctuation)

## Handling Emoji's

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 13.0 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
import emoji
def handling_emoji(text):
    emoji1 = emoji.emoji_list(text)
    for i in emoji1:
        # print(i['emoji'])
        text=text.replace(i['emoji'],'')
    return text

In [ ]:
df['tweet_content']=df['tweet_content'].apply(handling_emoji)

In [ ]:
df2['tweet_content']=df2['tweet_content'].apply(handling_emoji)

In [ ]:
def text_process(mess):

    STOPWORDS = stopwords.words('english') + ['u', 'ü', 'ur', '4', '2', 'im', 'dont', 'doin', 'ure']
    # Check characters to see if they are in punctuation
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)

    # Now just remove any stopwords
    return ' '.join([word for word in nopunc.split() if word.lower() not in STOPWORDS])

In [ ]:

resources = [
    'stopwords',
    'punkt',
    'wordnet',
    'omw-1.4',
    'averaged_perceptron_tagger'
]

for resource in resources:
    nltk.download(resource)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [ ]:
df['tweet_content']=df['tweet_content'].apply(text_process)

In [ ]:
df2['tweet_content']=df2['tweet_content'].apply(text_process)

In [ ]:
df.duplicated().sum()

np.int64(8898)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df2.duplicated().sum()

np.int64(4)

In [ ]:
df2.drop_duplicates(inplace=True)

## Labeling the Sentiment Column

In [ ]:
le=LabelEncoder()

In [ ]:
df['sentiment']=le.fit_transform(df['sentiment'])

In [ ]:
df2['sentiment']=le.transform(df2['sentiment'])

In [ ]:
BATCH_SIZE=8

## Tokenization

In [ ]:
model_id="bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_id)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
def tokenize_function(examples):
    return tokenizer(
        examples["tweet_content"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

In [ ]:
dataset = Dataset.from_pandas(df)

In [ ]:
dataset2 = Dataset.from_pandas(df2)

In [ ]:
train_dataset = dataset.map(tokenize_function, batched=True)
test_dataset = dataset2.map(tokenize_function, batched=True)

Map:   0%|          | 0/62757 [00:00<?, ? examples/s]

Map:   0%|          | 0/995 [00:00<?, ? examples/s]

## Raname Column to Labels

In [ ]:
train_dataset = train_dataset.rename_column("sentiment", "labels")
test_dataset = test_dataset.rename_column("sentiment", "labels")

## Removing the text Column

In [ ]:
train_dataset = train_dataset.remove_columns(["tweet_content"])
test_dataset = test_dataset.remove_columns(["tweet_content"])

In [ ]:
print(type(train_dataset))

<class 'datasets.arrow_dataset.Dataset'>

## Loading a Model

In [ ]:
MODEL_NAME = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=4      # Positive, Negative, Neutral, Irrelevant
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Training Configuration

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
)

In [ ]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

In [ ]:
data_collator = DefaultDataCollator()

## Training

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=11769, training_loss=0.4603046822724159, metrics={'train_runtime': 3878.1568, 'train_samples_per_second': 48.547, 'train_steps_per_second': 3.035, 'total_flos': 1.2384267758613504e+16, 'train_loss': 0.4603046822724159, 'epoch': 3.0})

## Evaluate Results

In [ ]:
eval_results = trainer.evaluate()

print(eval_results)

{'eval_loss': 0.16682849824428558, 'eval_accuracy': 0.9597989949748744, 'eval_precision': 0.9599890913639592, 'eval_recall': 0.9597989949748744, 'eval_f1': 0.9597697115226376}

## Conclusion


*   Accuracy : 0.959
*   f1_score : 0.959
*   Training Loss : 0.170
*   Validation Loss : 0.166